[project]
name = "blueshch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    django==5.2.4
    python-decouple==3.8
    requests==2.32.4
    django-tailwind==4.2.0
]
